### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Sander-Toonen** [mac-cain13/iDealBundle#7]
Good to see there is a Symfony Bundle for iDeal, however, it looks like this bundle is not actively maintained? Is that correct? Will there be documentation soon?

**Comment by mac-cain13** [comment]
Hey @Sander-Toonen, this bundle is used in one small project and is not maintained by me anymore. 

I would advise to use it as an starting point if there is no other bundle that supports your use case. But expect that you have to dive into it and their might be missing features. The features that are there should work as expected, but I haven't used it in a Symfony 3 for example.

If you are willing to spend some time on it and use it in a project I could help review some PRs or even add you as a collaborator so you have push access.

Let me know if you're interested in something like that.
